"""The /review monitor's stylesheet, after the Claude Design mock-up.

Colours are the mock-up's tokens, light and dark. Desktop has a sidebar and a
640 px column, with a 380 px gutter kept free on wide screens for a later Ask
panel; below 760 px the sidebar gives way to a top bar and a bottom tab bar.
Fonts are the system's: the Content-Security-Policy allows no outside requests.
Standard library only.
"""

from __future__ import annotations

SERIF = "Georgia,'Times New Roman',Times,serif"
MONO = "ui-monospace,SFMono-Regular,Menlo,Consolas,'Liberation Mono',monospace"
LIGHT = (
    "--bg:#FAF9F5;--panel:#FFFFFF;--side:#F0EEE6;--line:#E3E0D6;--line2:#F0EEE6;--ink:#141413;"
    "--ink2:#3D3D3A;--muted:#5E5D59;--accent:#B8532F;--accentbg:#FBF1EC;--okfg:#2E5A36;"
    "--okbg:#E7EEE6;--okdot:#3D7A48;--warnfg:#9A4424;--warnbg:#F5E6DF;--badfg:#9B1C1C;"
    "--badbg:#FBE9E7;--badln:#E8A9A2;--code:#F5F3EC;--sw_on:#D97757;--sw_off:#D1CEC4;"
    "--knob:#FFFFFF;--fade:#8A877D"
)
DARK = (
    "--bg:#1C1B19;--panel:#262522;--side:#22211E;--line:#3A3833;--line2:#302E2A;--ink:#F0EEE6;"
    "--ink2:#D3CFC4;--muted:#A8A499;--accent:#E8906C;--accentbg:#3A2820;--okfg:#A7D0AE;"
    "--okbg:#223328;--okdot:#6FB07B;--warnfg:#F2AE8C;--warnbg:#3E2A20;--badfg:#F6A9A9;"
    "--badbg:#3E1F1F;--badln:#7A3434;--code:#201F1C;--sw_on:#C9694A;--sw_off:#4A4842;"
    "--knob:#E8E5DC;--fade:#8F8B80"
)
CSS = (
    f":root{{{LIGHT}}}@media (prefers-color-scheme:dark){{:root{{{DARK}}}}}"
    "*{box-sizing:border-box}html{color-scheme:light dark}"
    "body{margin:0;background:var(--bg);color:var(--ink);"
    "font:15px/1.45 system-ui,-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif}"
    "a{color:var(--ink)}a:hover{color:var(--accent)}"
    ".app{display:flex;min-height:100vh}"
    ".side{width:260px;flex-shrink:0;background:var(--side);border-right:1px solid var(--line);"
    "padding:20px 12px;display:flex;flex-direction:column;gap:4px}"
    f".brand{{padding:8px 12px 16px;font-family:{SERIF};font-size:20px}}"
    ".group{padding:0 12px 6px;font-size:12px;color:var(--muted)}"
    ".wsgroup{margin:16px 0 8px;padding:16px 12px 0;border-top:1px solid var(--line);"
    "display:flex;flex-direction:column;gap:2px}.wsgroup b{display:flex;align-items:center;"
    "gap:8px;font-size:15px;font-weight:600}.wsgroup a{font-size:13px;color:var(--muted)}"
    ".nav{display:flex;align-items:center;gap:12px;min-height:44px;padding:0 12px;"
    "border-radius:10px;text-decoration:none;font-size:15px;color:var(--ink2)}"
    ".nav.on{background:var(--line);font-weight:600;color:var(--ink)}"
    ".who{margin-top:auto;display:flex;align-items:center;gap:12px;padding:12px;"
    "border-top:1px solid var(--line)}"
    ".avatar{width:32px;height:32px;border-radius:999px;background:var(--ink);color:var(--bg);"
    "display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:600}"
    ".who div span{display:block;font-size:14px;font-weight:500}.who small{font-size:12px;"
    "color:var(--muted)}"
    ".col{flex-grow:1;min-width:0;display:flex;flex-direction:column}"
    "main{width:100%;max-width:640px;padding:44px 40px 56px;display:flex;"
    "flex-direction:column;gap:22px}"
    ".gutter{width:380px;flex-shrink:0}@media (max-width:1279px){.gutter{display:none}}"
    ".top,.tabs{display:none}"
    ".head{display:flex;flex-direction:column;gap:6px}"
    ".crumb{font-size:14px;color:var(--muted)}.crumb a{color:inherit}"
    f"h1{{margin:0;font-family:{SERIF};font-weight:400;font-size:32px;line-height:1.2;"
    "overflow-wrap:anywhere}"
    f"h2{{margin:0;font-family:{SERIF};font-weight:400;font-size:22px}}"
    "h3{margin:0;font-size:15px;font-weight:600}"
    ".lede{font-size:15px;color:var(--ink2)}.muted{font-size:13px;color:var(--muted)}"
    ".status{display:flex;flex-wrap:wrap;align-items:center;gap:8px 14px;font-size:14px;"
    "color:var(--ink2)}.status span{display:inline-flex;align-items:center;gap:6px}"
    ".okline{color:var(--okfg)}"
    ".card{background:var(--panel);border:1px solid var(--line);border-radius:16px;"
    "padding:20px;display:flex;flex-direction:column;gap:14px;min-width:0}"
    ".card.flush{padding:0;gap:0}a.card{text-decoration:none;color:var(--ink)}"
    ".bar{display:flex;justify-content:space-between;align-items:center;gap:8px 12px;"
    "flex-wrap:wrap}.bar>span{display:flex;align-items:center;gap:8px;font-size:13px;"
    "color:var(--muted)}"
    ".kv{display:flex;justify-content:space-between;gap:16px;padding:9px 0;"
    "border-bottom:1px solid var(--line2);font-size:14px;flex-wrap:wrap}"
    ".kv:last-child{border-bottom:0}.kv>span:first-child{color:var(--muted)}"
    ".kv>span:last-child{text-align:right;overflow-wrap:anywhere}"
    ".stats{display:flex;flex-wrap:wrap;gap:10px}"
    ".stat{flex:1 1 130px;background:var(--bg);border:1px solid var(--line2);border-radius:12px;"
    "padding:12px 14px;display:flex;flex-direction:column;gap:2px}"
    f".stat small{{font-size:12px;color:var(--muted)}}.stat b{{font-family:{SERIF};"
    "font-size:22px;font-weight:400}"
    ".row{display:flex;align-items:center;gap:12px;min-height:52px;padding:10px 16px;"
    "border-bottom:1px solid var(--line2);text-decoration:none;color:var(--ink)}"
    ".row:last-child{border-bottom:0}.row .grow{flex-grow:1;display:flex;flex-direction:column;"
    "gap:2px;min-width:0}.row .grow>span:first-child{font-size:15px;font-weight:500;"
    "overflow-wrap:anywhere}.row .grow>span+span{font-size:13px;color:var(--muted);"
    "overflow-wrap:anywhere}.row .end{display:flex;align-items:center;gap:8px;flex-shrink:0}"
    ".pill{display:inline-flex;align-items:center;gap:4px;font-size:12px;line-height:1.4;"
    "color:var(--muted);padding:2px 8px;border-radius:6px;background:var(--line2);"
    "white-space:nowrap}"
    ".pill.ok{color:var(--okfg);background:var(--okbg)}"
    ".pill.warn{color:var(--warnfg);background:var(--warnbg)}"
    ".pill.bad{color:var(--badfg);background:var(--badbg)}"
    ".pill.accent{color:var(--accent);background:var(--accentbg)}"
    ".pill.lock{background:none;border:1px dashed var(--fade)}"
    ".sw{display:inline-flex;align-items:center;gap:6px;font-size:13px;white-space:nowrap}"
    ".sw i{width:26px;height:14px;border-radius:999px;background:var(--sw_off);display:inline-flex;"
    "align-items:center;padding:2px}.sw i:after{content:'';width:10px;height:10px;"
    "border-radius:999px;background:var(--knob)}.sw.on{color:var(--okfg)}"
    ".sw.on i{background:var(--sw_on);justify-content:flex-end}"
    f".mono{{font-family:{MONO};font-size:13px}}"
    f".code{{font-family:{MONO};font-size:12px;line-height:1.6;background:var(--code);"
    "border:1px solid var(--line2);border-radius:10px;padding:12px 14px;white-space:pre-wrap;"
    "word-break:break-word;margin:0;color:var(--ink)}.code.big{font-size:13px}"
    ".code .k{color:var(--ink2)}.code .s{color:var(--okfg)}.code .v{color:var(--accent)}"
    ".code .c{color:var(--muted)}"
    ".more{color:var(--accent);font-size:14px;display:inline-flex;align-items:center;gap:4px;"
    "min-height:32px}"
    ".alert{border-radius:16px;padding:14px 16px;display:flex;gap:10px;align-items:flex-start;"
    "font-size:14px}.alert.warn{background:var(--warnbg)}.alert.warn>svg{color:var(--warnfg)}"
    ".alert.bad{background:var(--badbg);border:1px solid var(--badln)}"
    ".alert.bad>svg{color:var(--badfg)}.alert.bad strong{color:var(--badfg)}"
    ".alert>svg{flex-shrink:0;margin-top:2px}.alert div{display:flex;flex-direction:column;gap:6px}"
    ".param{display:flex;flex-wrap:wrap;gap:4px 10px;align-items:baseline;padding:8px 0;"
    "border-top:1px solid var(--line2)}.param>span:last-child{flex-basis:100%;font-size:13px;"
    "color:var(--ink2)}.param small{font-size:12px;color:var(--muted)}"
    ".steps{margin:0;padding:0;display:flex;flex-direction:column;gap:10px}"
    ".steps li{list-style:none;border:1px solid var(--line2);background:var(--panel);"
    "border-radius:12px;padding:12px 14px;display:flex;flex-direction:column;gap:8px;min-width:0}"
    ".steps li.leak{border:2px solid var(--warnfg);background:var(--warnbg)}"
    ".steps .args{font-size:13px;color:var(--ink2);overflow-wrap:anywhere}"
    ".msgs{display:flex;flex-direction:column;gap:14px}"
    ".msg{display:flex;flex-direction:column;gap:4px}.msg small{font-size:12px;color:var(--muted)}"
    ".msg div{background:var(--panel);border:1px solid var(--line2);border-radius:12px;"
    "padding:10px 14px;font-size:15px;line-height:1.55;white-space:pre-wrap;"
    "overflow-wrap:anywhere}.msg.you div{background:var(--line2)}.msgs.out .msg{opacity:.55}"
    ".ctx{border-left:4px solid var(--accent);background:var(--accentbg);"
    "border-radius:0 16px 16px 0;padding:14px 14px 16px 16px;display:flex;"
    "flex-direction:column;gap:14px}"
    ".admin{border-top:1px dashed var(--fade);padding-top:20px;margin-top:8px;display:flex;"
    "flex-direction:column;gap:14px}.admin h2{font-size:20px;color:var(--ink2)}"
    "details summary{cursor:pointer;min-height:32px;font-size:14px;color:var(--ink2)}"
    ".prompt{font-size:14px;line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere}"
    "@media (max-width:760px){.side{display:none}"
    ".top{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;"
    f"border-bottom:1px solid var(--line)}}.top b{{font-family:{SERIF};font-size:18px;"
    "font-weight:400}.top span{font-size:13px;color:var(--muted)}"
    "main{max-width:none;padding:20px 16px 96px;gap:18px}"
    ".tabs{display:flex;position:fixed;left:0;right:0;bottom:0;border-top:1px solid var(--line);"
    "background:var(--side);padding:0 4px 20px}"
    ".tabs a{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;"
    "gap:2px;min-height:56px;text-decoration:none;font-size:11px;color:var(--muted)}"
    ".tabs a.on{color:var(--accent);font-weight:600}.card{padding:16px}}"
)
