---
- name: Reload diot user systemd
  become_user: "{{ diot_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ diot_runtime_dir }}"
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true
